name: CI

on:
  push:
  pull_request:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Make scripts executable
        run: chmod +x *.sh || true

      - name: Install shellcheck
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck

      - name: Run shellcheck (lint)
        run: |
          # Lint all shell scripts at repo root; expand or tweak the glob if needed
          shellcheck -x Marz.Migrator.sh

      - name: Syntax check (bash -n)
        run: |
          bash -n Marz.Migrator.sh
